version: '3.8'

services:
  web:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run dev
